version: 2.1
jobs:
  build:
    docker:
      - image: cimg/rust:1.81.0-node
    steps:
      - checkout
      - attach_workspace:
          at: ~/workspace
      - add_ssh_keys:
          fingerprints:
            - "SHA256:jL0sv9h2M5JzXUxPtOvH/VeYCxY6wZPVXt8v9I+QYD4"
      - run:
          name: Clone BinahBotConfig repository
          command: >-
            GIT_SSH_COMMAND='ssh -i ~/.ssh/id_rsa_fingerprint'
            git clone git@github.com:Ghoulean/BinahBotConfig.git ~/BinahBotConfig
      - run:
          name: Copy CDK env to the respective location
          command: cp ~/BinahBotConfig/cdk.env ~/workspace/ruina-cdk
      - run:
          name: Copy channel configuration to the respective location
          command: cp ~/BinahBotConfig/channel_config.toml ~/workspace/rust/binah_bot/binah_bot_spoiler/src/channel_config.toml
      - run:
          name: cargo build BinahBot
          command: cd ~/workspace/rust/binah_bot && cargo bb
      - run:
          name: cargo build Thumbnail Lambda
          command: cd ~/workspace/rust/thumbnail && cargo bb
      - run:
          name: cdk build
          command: cd ~/workspace/ruina-cdk && npm run build
  test:
    docker:
      - image: cimg/rust:1.81.0-node
    steps:
      - run:
          name: Run all tests
          command: cd ~/workspace/rust && cargo test --all-targets
  onetime-setup:
    docker:
      - image: cimg/rust:1.81.0-node
    steps:
      - run:
          name: Ensure commands for BinahBot are up to date
          command: cd ~/workspace/ruina-discord-bot-onetime-setup && npm run discord:write    
  deploy-to-aws:
    # This is an example deploy job, not actually used by the workflow
    docker:
      - image: cimg/rust:1.81.0-node
    steps:
      # Replace this with steps to deploy to users
      - run:
          name: deploy
          command: cargo --version; node --version
workflows:
  deploy-to-prod:
    jobs:
      - build
      - test:
          requires:
            - build
      - onetime-setup:
          filters:
            branches:
              only:
                - main
          requires:
            - test
      - deploy-to-aws:
          filters:
            branches:
              only:
                - main
          requires:
            - test

