[workspace]
resolver = "2"

members = [
    "binah_bot",
    "binah_bot/binah_bot_spoiler",
    "ruina_common",
    "ruina_index",
    "ruina_index/ruina_index_analyzer",
    "ruina_index/ruina_index_builder",
    "ruina_reparser",
    "ruina_reparser/ruina_reparser_build"
]
